# Generated by Django 5.2.6 on 2025-09-04 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('user', 'User')], default='user', max_length=20),
        ),
        migrations.CreateModel(
            name='DjangoUserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('user_email', models.CharField(max_length=254)),
                ('activity_type', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('search', 'Search'), ('image_search', 'Image Search'), ('voice_search', 'Voice Search'), ('page_view', 'Page View')], max_length=20)),
                ('activity_data', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_activities',
                'indexes': [models.Index(fields=['user_id'], name='user_activi_user_id_260c6d_idx'), models.Index(fields=['activity_type'], name='user_activi_activit_534635_idx'), models.Index(fields=['timestamp'], name='user_activi_timesta_12eff7_idx')],
            },
        ),
        migrations.CreateModel(
            name='DjangoUserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('user_email', models.CharField(max_length=254)),
                ('user_name', models.CharField(max_length=100)),
                ('session_key', models.CharField(max_length=100, unique=True)),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('is_active', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_sessions',
                'indexes': [models.Index(fields=['user_id'], name='user_sessio_user_id_eb20aa_idx'), models.Index(fields=['session_key'], name='user_sessio_session_cc84b9_idx'), models.Index(fields=['is_active'], name='user_sessio_is_acti_1b3cb1_idx'), models.Index(fields=['last_activity'], name='user_sessio_last_ac_7cb421_idx')],
            },
        ),
    ]
